// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9XOIF-NyyFYxWLLQd3ppK_B_7VOYkwg',
    appId: '1:1029154810739:web:4272ddb8de8e81384bf306',
    messagingSenderId: '1029154810739',
    projectId: 'flutterxfirebase-1495a',
    authDomain: 'flutterxfirebase-1495a.firebaseapp.com',
    storageBucket: 'flutterxfirebase-1495a.appspot.com',
    measurementId: 'G-YNZL4H7LNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8XaQFUi3YQhQu7BlCkHZBYko775aoOc',
    appId: '1:1029154810739:android:99b6c4a5e4c5f61e4bf306',
    messagingSenderId: '1029154810739',
    projectId: 'flutterxfirebase-1495a',
    storageBucket: 'flutterxfirebase-1495a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxheNc-ZjEHMfZNml659G5ZqIrkWyTag',
    appId: '1:1029154810739:ios:fb2a3287c76d3f884bf306',
    messagingSenderId: '1029154810739',
    projectId: 'flutterxfirebase-1495a',
    storageBucket: 'flutterxfirebase-1495a.appspot.com',
    iosBundleId: 'com.example.flutterxfirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvxheNc-ZjEHMfZNml659G5ZqIrkWyTag',
    appId: '1:1029154810739:ios:838c59065570c1d34bf306',
    messagingSenderId: '1029154810739',
    projectId: 'flutterxfirebase-1495a',
    storageBucket: 'flutterxfirebase-1495a.appspot.com',
    iosBundleId: 'com.example.flutterxfirebase1.RunnerTests',
  );
}
